# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: cimg/node:18.18.2
    steps: 
      - add_ssh_keys:
          fingerprints:
            - "71:93:50:d1:4d:1b:18:1f:1c:1c:81:5d:f0:46:66:8a"
      - checkout
      - restore_cache:
          keys:
            - dependencies_demo
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_demo
      - run:
          name: Build
          command: yarn build
      - run:
          name: Prepare shell commands
          # shell chmod +x 赋予执行权限
          # 执行shell脚本
          command: chmod +777 scripts/deploy.sh
      - run:
          name: Run Deploy to GitHub pages
          command: sh ./scripts/deploy.sh