# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: cimg/node:18.18.2
    branches:
      only:
        - master
    steps: 
      - run: echo "A first circle"
      - run: npm -v