# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: cimg/node:18.18.2
    steps: 
      - add_ssh_keys:
          fingerprints:
            - "71:93:50:d1:4d:1b:18:1f:1c:1c:81:5d:f0:46:66:8a"
      - checkout 
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build